version: "3.9"

services:
  database:
    image: postgres:18-alpine
    container_name: teleconsulta-db
    environment:
      POSTGRES_DB: teleconsulta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - teleconsulta-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: teleconsulta-app
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: teleconsulta
      DB_USER: postgres
      DB_PASS: postgres
    networks:
      - teleconsulta-net

volumes:
  postgres_data:

networks:
  teleconsulta-net:
